package livery

import (
	"context"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// TestCNCFCatalogLoads asserts the embedded manifest parses into a usable
// catalog, and that the default selection is actually in it.
func TestCNCFCatalogLoads(t *testing.T) {
	projects := CNCFProjects()
	if len(projects) < 100 {
		t.Fatalf("catalog has %d projects, want the full cncf/artwork set", len(projects))
	}
	if _, ok := LookupCNCF(DefaultCNCFID); !ok {
		t.Errorf("default project %q is not in the catalog", DefaultCNCFID)
	}
	for _, p := range projects {
		if p.ID == "" || p.Name == "" || p.path == "" {
			t.Fatalf("incomplete catalog entry %+v", p)
		}
	}
}

// TestCNCFPathsAreNotDerivedFromIDs is the regression test for the 30
// projects whose artwork filename does not follow <id>-icon-color.svg.
// Deriving the name instead of storing it would 404 on exactly those.
func TestCNCFPathsAreNotDerivedFromIDs(t *testing.T) {
	var nonCanonical int
	for _, p := range CNCFProjects() {
		if !strings.HasSuffix(p.path, p.ID+"-icon-color.svg") {
			nonCanonical++
		}
	}
	if nonCanonical == 0 {
		t.Fatal("no non-canonical artwork paths found; the manifest may have been regenerated by derivation, which would break those projects")
	}
	if _, ok := LookupCNCF("cilium"); !ok {
		t.Error("cilium missing: it is one of the non-canonical cases this test guards")
	}
}

// TestNextCNCFIDWrapsAndIsTotal asserts dock rotation is deterministic and
// can never leave the selection unset.
func TestNextCNCFIDWrapsAndIsTotal(t *testing.T) {
	projects := CNCFProjects()
	last := projects[len(projects)-1].ID
	if got := NextCNCFID(last); got != projects[0].ID {
		t.Errorf("NextCNCFID(%q) = %q, want wrap to %q", last, got, projects[0].ID)
	}
	for _, id := range []string{"", CustomID, "not-a-project"} {
		if got := NextCNCFID(id); got != projects[0].ID {
			t.Errorf("NextCNCFID(%q) = %q, want %q", id, got, projects[0].ID)
		}
	}
}

// TestCNCFIconFetchUsesTheManifestPath asserts the request targets the path
// the manifest records, not a derived one.
func TestCNCFIconFetchUsesTheManifestPath(t *testing.T) {
	var requested string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requested = r.URL.Path
		_, _ = w.Write([]byte(`<svg viewBox="0 0 24 24"><path d="M1 1h2v2H1z"/></svg>`))
	}))
	defer server.Close()

	original := Fetch
	Fetch = func(ctx context.Context, url string) ([]byte, error) {
		return httpFetch(ctx, server.URL+"/"+strings.TrimPrefix(url, cncfArtworkRaw))
	}
	t.Cleanup(func() { Fetch = original })

	if _, err := FetchCNCFIcon(context.Background(), "cilium"); err != nil {
		t.Fatalf("FetchCNCFIcon: %v", err)
	}
	if !strings.Contains(requested, "cilium_icon-color.svg") {
		t.Errorf("requested %q, want cilium's real non-canonical filename", requested)
	}
}

// TestCNCFIconFetchRejectsAnUnknownProject asserts an id outside the catalog
// never reaches the network.
func TestCNCFIconFetchRejectsAnUnknownProject(t *testing.T) {
	original := Fetch
	var called bool
	Fetch = func(context.Context, string) ([]byte, error) {
		called = true
		return nil, errors.New("should not be reached")
	}
	t.Cleanup(func() { Fetch = original })

	if _, err := FetchCNCFIcon(context.Background(), "definitely-not-a-project"); err == nil {
		t.Fatal("accepted a project outside the catalog")
	}
	if called {
		t.Error("an unknown project reached the network")
	}
}

// TestSearchRanksPrefixMatchesFirst asserts typing a project's own name puts
// it at the top rather than burying it behind incidental substring hits.
func TestSearchRanksPrefixMatchesFirst(t *testing.T) {
	results := SearchCNCF("etcd", 10)
	if len(results) == 0 {
		t.Fatal("no results for etcd")
	}
	if results[0].ID != "etcd" {
		t.Errorf("first result for %q is %q, want etcd", "etcd", results[0].ID)
	}
}

// TestSearchMatchesPartialNames covers the ordinary case of typing a few
// letters, and that the cap is honoured.
func TestSearchMatchesPartialNames(t *testing.T) {
	results := SearchCNCF("kube", 3)
	if len(results) != 3 {
		t.Fatalf("got %d results, want the 3 requested", len(results))
	}
	for _, p := range results {
		if !strings.Contains(strings.ToLower(p.ID), "kube") &&
			!strings.Contains(strings.ToLower(p.Name), "kube") {
			t.Errorf("%q does not match the query", p.ID)
		}
	}
}

// TestEmptySearchShowsTheCatalogHead asserts the list is populated before the
// user types anything, so the section never looks broken on arrival.
func TestEmptySearchShowsTheCatalogHead(t *testing.T) {
	results := SearchCNCF("", 5)
	if len(results) != 5 {
		t.Fatalf("empty query returned %d results, want 5", len(results))
	}
}

// TestSearchWithNoMatchesReturnsEmpty asserts a nonsense query yields nothing
// rather than the whole catalog.
func TestSearchWithNoMatchesReturnsEmpty(t *testing.T) {
	if results := SearchCNCF("zzzznotaproject", 10); len(results) != 0 {
		t.Errorf("got %d results for a nonsense query, want 0", len(results))
	}
}

// TestDisplayNamesComeFromTheArtworkRepository asserts the catalog uses the
// names cncf/artwork publishes rather than title-casing directory names,
// which produces "Cloudcustodian", "Opentelemetry", and "Etcd".
func TestDisplayNamesComeFromTheArtworkRepository(t *testing.T) {
	want := map[string]string{
		"cloudcustodian": "Cloud Custodian",
		"opentelemetry":  "OpenTelemetry",
		"etcd":           "etcd",
		"k0s":            "k0s",
	}
	for id, name := range want {
		project, ok := LookupCNCF(id)
		if !ok {
			t.Errorf("%q missing from the catalog", id)
			continue
		}
		if project.Name != name {
			t.Errorf("%q displays as %q, want %q", id, project.Name, name)
		}
	}
}

// TestSearchFindsAProjectByEitherWord covers the case that exposed the naming
// problem: a user typing "custodian" must find Cloud Custodian even though
// the directory is one word.
func TestSearchFindsAProjectByEitherWord(t *testing.T) {
	for _, query := range []string{"cloud custodian", "custodian", "cloudcustodian"} {
		var found bool
		for _, p := range SearchCNCF(query, 50) {
			if p.ID == "cloudcustodian" {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("searching %q did not find cloudcustodian", query)
		}
	}
}
